# kubectl apply -f 01-mutatingwebhook.yaml -n kube-ksidecar
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: ksidecar-injector
webhooks:
  - name: ksidecar.github.com # 必须是3段域名
    clientConfig:
      service:
        name: ksidecar-injector
        namespace: kube-ksidecar
        path: "/mutate"
      caBundle: <BASE64(ca.pem),未指定使用k8s api server CA>
    failurePolicy: Fail
    sideEffects: None
    admissionReviewVersions:
      - v1
    rules:
      - apiGroups:
          - ""
        resources:
          - pods
        apiVersions:
          - "*"
        operations:
          - CREATE
        scope: Namespaced
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
            - kube-public
            - kube-ksidecar
        - key: ksidecar/inject
          operator: In
          values:
            - "enable"
            - "true"
    objectSelector:
      matchExpressions:
        - key: ksidecar/inject
          operator: In
          values:
            - "enable"
            - "true"

