---
apiVersion: v1
kind: Secret
metadata:
  name: ksidecar-injector-certs
stringData:
  ca.pem: |-
    <PEM..., 根证书,k8s调用时,使用>
  crt.pem: |-
    <PEM..., ksidecar-injector.kube-ksidecar.svc证书>
  key.pem: |-
    <PEM..., ksidecar-injector.kube-ksidecar.svc密钥>
