# kubectl apply -f 13-deployment.yaml -n kube-ksidecar
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ksidecar-injector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ksidecar-injector
  template:
    metadata:
      labels:
        app: ksidecar-injector
    spec:
      serviceAccountName: ksidecar-injector
      containers:
        - name: kube-sidecar-injector
          image: suisrc/sidecar-injector:0.0.2
          imagePullPolicy: IfNotPresent
          args:
            - --port=443
            - --certFile=/opt/certs/crt.pem
            - --keyFile=/opt/certs/key.pem
            - --injectPrefix=ksidecar
            - --injectName=configmap
            - --sidecarDataKey=sidecar.yaml
          volumeMounts:
            - name: certs
              mountPath: /opt/certs
              readOnly: true
          ports:
            - name: https
              containerPort: 443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 4
          readinessProbe:
            httpGet:
              path: /healthz
              port: https
              scheme: HTTPS
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
            timeoutSeconds: 4
      volumes:
        - name: certs
          secret:
            secretName: ksidecar-injector-certs
